application: homepagejerry
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /images
  static_dir: public/images

- url: /pdf
  static_dir: public/pdf

- url: /video
  static_dir: public/video

- url: /comp4021
  static_dir: public/comp4021

- url: /css
  static_dir: public/css

- url: /fonts
  static_dir: public/fonts

- url: /js
  static_dir: public/js


